name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild -configuration Release
      - name: Zip the driver package
        run: |
          zip -r Artifacts.zip ./build/El\ Capitan/GenericUSBXHCI.kext
      - name: Upload the driver package
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/El\ Capitan/*
